name: bookyp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter_dotenv: ^5.0.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  logger: ^1.0.0
  provider: ^5.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - .env
    - assets/rive/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
